# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "hbsmith/awslinux"

  config.vm.provider "virtualbox" do |v|
    v.name = 'SpringThrottlingExample'
    v.cpus = 4
    v.memory = 2048
  end

  config.vm.provision "shell", inline: "yum -y install python36"
  config.vm.provision "shell", path: "provisioning.py", args: "vagrant"
  config.vm.network "private_network", ip: "192.168.88.100"
end
